# Generated by Django 2.2.4 on 2019-08-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190808_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='06', max_length=15),
            preserve_default=False,
        ),
    ]
