# Generated by Django 2.2.4 on 2019-08-12 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190809_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Asset', unique=True),
        ),
    ]
