# Generated by Django 2.2.4 on 2019-08-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190807_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(default='companx_item1_id2', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
